<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IN-MH1LPW101884" failures="1" tests="6" name="smapletest.loginTest" time="82.317" errors="0" timestamp="2021-02-26T11:52:27 IST" skipped="3">
  <testcase classname="smapletest.loginTest" name="loginTest04" time="3.731"/>
  <system-out/>
  <testcase classname="smapletest.loginTest" name="loginTest02" time="40.211"/>
  <system-out/>
  <testcase classname="smapletest.loginTest" name="loginTest01" time="38.375">
    <failure message="expected:&lt;https://opensource-demo.orangehrmlive.com/index.php/auth/login&gt; but was:&lt;https://opensource-demo.orangehrmlive.com/index.php/dashboard&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<https://opensource-demo.orangehrmlive.com/index.php/auth/login> but was:<https://opensource-demo.orangehrmlive.com/index.php/dashboard>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at helper.helper.isLoginSuccessful(helper.java:19)
at smapletest.loginTest.loginTest01(loginTest.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginTest01 -->
  <system-out/>
  <testcase classname="smapletest.loginTest" name="loginTest06">
    <skipped/>
  </testcase> <!-- loginTest06 -->
  <system-out/>
  <testcase classname="smapletest.loginTest" name="loginTest03">
    <skipped/>
  </testcase> <!-- loginTest03 -->
  <system-out/>
  <testcase classname="smapletest.loginTest" name="loginTest05">
    <skipped/>
  </testcase> <!-- loginTest05 -->
  <system-out/>
</testsuite> <!-- smapletest.loginTest -->
